In [1]:
import pandas as pd
import pycountry_convert as pc

GDP_PATH = "/Users/tonytony/gdp.csv"

gdp_df = pd.read_csv(GDP_PATH, skiprows=4)
print("Shape:", gdp_df.shape)
gdp_df.head()

Shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [2]:
gdp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            156 non-null    float64
 7   1963            156 non-null    float64
 8   1964            156 non-null    float64
 9   1965            162 non-null    float64
 10  1966            163 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            260 non-null    float64
 60  2016            259 non-null    float64
 61  2017            259 non-null    float64
 62  2018            259 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            257 non-null    float64
 67  2023            251 non-null    float64
 68  2024            240 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB

In [3]:
print("Number of rows:", gdp_df.shape[0])
print("Number of columns:", gdp_df.shape[1])
print("\nColumns:")
print(gdp_df.columns.tolist())

Number of rows: 266
Number of columns: 70

Columns:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', 'Unnamed: 69']

## Phân loại cột numerical và categorical

Cell này chia các cột thành 2 nhóm chính:
- `numerical columns`: các cột năm như `1960`, `1961`, ..., `2024`,
- `categorical columns`: các cột mô tả như `Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`.

Việc phân loại này quan trọng vì:
- nhóm numerical sẽ được dùng cho thống kê mô tả, missing values và visualization,
- nhóm categorical sẽ được dùng để nhận diện quốc gia, mã nước và metadata của dataset.

In [4]:
numerical_cols = [col for col in gdp_df.columns if str(col).isdigit()]
categorical_cols = [col for col in gdp_df.columns if col not in numerical_cols]

print("Numerical columns:", len(numerical_cols))
print(numerical_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

Numerical columns: 65
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

Categorical columns: 5
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 69']

## Kiểm tra số lượng giá trị duy nhất bằng `nunique()`

Cell này tính số lượng giá trị duy nhất của từng cột.

Bước này giúp trả lời các câu hỏi như:
- có bao nhiêu quốc gia hoặc vùng khác nhau trong dataset,
- `Indicator Name` có bao nhiêu loại,
- `Indicator Code` có bao nhiêu loại,
- các cột năm có bao nhiêu giá trị khác nhau.

Kết quả `nunique()` rất hữu ích để phát hiện:
- cột chỉ chứa 1 giá trị lặp đi lặp lại,
- cột có tính phân biệt cao như mã quốc gia,
- hoặc các cột không mang nhiều thông tin.

In [5]:
gdp_nunique = pd.DataFrame({
    "column": gdp_df.columns,
    "dtype": gdp_df.dtypes.astype(str).values,
    "nunique": [gdp_df[col].nunique(dropna=True) for col in gdp_df.columns]
})

gdp_nunique

            column    dtype  nunique
0     Country Name      str      266
1     Country Code      str      266
2   Indicator Name      str        1
3   Indicator Code      str        1
4             1960  float64      150
..             ...      ...      ...
65            2021  float64      256
66            2022  float64      255
67            2023  float64      249
68            2024  float64      238
69     Unnamed: 69  float64        0

[70 rows x 3 columns]

## Kiểm tra số lượng giá trị thiếu

Cell này tạo bảng tóm tắt missing values cho từng cột, bao gồm:
- `null_count`: số lượng giá trị thiếu,
- `null_ratio_pct`: tỷ lệ phần trăm giá trị thiếu,
- `dtype`: kiểu dữ liệu của cột.

Đây là bước quan trọng để đánh giá chất lượng dữ liệu.  
Nếu một cột có tỷ lệ thiếu cao, đặc biệt là các cột năm đầu hoặc năm mới nhất, thì cần lưu ý khi phân tích.

In [6]:
gdp_null = pd.DataFrame({
    "column": gdp_df.columns,
    "null_count": gdp_df.isnull().sum().values,
    "null_ratio_pct": (gdp_df.isnull().mean() * 100).round(2).values,
    "dtype": gdp_df.dtypes.astype(str).values
}).sort_values(["null_count", "column"], ascending=[False, True])

gdp_null

            column  null_count  null_ratio_pct    dtype
69     Unnamed: 69         266          100.00  float64
4             1960         115           43.23  float64
5             1961         112           42.11  float64
6             1962         110           41.35  float64
7             1963         110           41.35  float64
..             ...         ...             ...      ...
55            2011           4            1.50  float64
1     Country Code           0            0.00      str
0     Country Name           0            0.00      str
3   Indicator Code           0            0.00      str
2   Indicator Name           0            0.00      str

[70 rows x 4 columns]

##  Xem các cột thiếu dữ liệu nhiều nhất

Cell này hiển thị các cột có số lượng missing values cao nhất.

Mục tiêu là:
- xác định nhanh cột nào đang có vấn đề về độ đầy đủ dữ liệu,
- xem các năm nào bị thiếu nhiều nhất,
- chuẩn bị cho phần nhận xét về chất lượng dữ liệu.

Với GDP, các năm đầu thường thiếu dữ liệu nhiều hơn so với các năm gần đây.

In [7]:
gdp_null.head(15)

         column  null_count  null_ratio_pct    dtype
69  Unnamed: 69         266          100.00  float64
4          1960         115           43.23  float64
5          1961         112           42.11  float64
6          1962         110           41.35  float64
7          1963         110           41.35  float64
8          1964         110           41.35  float64
9          1965         104           39.10  float64
10         1966         103           38.72  float64
11         1967          99           37.22  float64
12         1968          98           36.84  float64
13         1969          98           36.84  float64
14         1970          76           28.57  float64
15         1971          75           28.20  float64
16         1972          75           28.20  float64
17         1973          75           28.20  float64

## Thống kê mô tả cho các cột số bằng `describe()`

Cell này áp dụng `describe()` cho toàn bộ các cột numerical, tức là các cột năm.

Kết quả bao gồm:
- `count`: số lượng giá trị hợp lệ,
- `mean`: giá trị trung bình,
- `std`: độ lệch chuẩn,
- `min`: giá trị nhỏ nhất,
- `25%`, `50%`, `75%`: các phân vị,
- `max`: giá trị lớn nhất.

Bảng này giúp đánh giá nhanh phân phối GDP theo từng năm và phát hiện khả năng có outlier lớn.

In [8]:
gdp_df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
1960,151.0,471.801812,593.004639,25.084776,123.298251,221.559849,499.867270,2999.864872
1961,154.0,491.169565,616.999240,27.265454,127.469973,209.531940,538.358099,3059.160821
1962,156.0,538.650484,729.010673,27.947004,129.546141,217.376949,574.686135,4748.392844
1963,156.0,571.509413,753.033032,25.803984,138.894446,233.409578,610.222254,4444.523086
1964,156.0,617.797769,811.026840,17.332201,144.547396,244.104274,707.377633,4378.784298
...,...,...,...,...,...,...,...,...
2020,258.0,16283.153813,24311.651161,255.832454,2133.015667,6131.818702,19908.734345,176891.886538
2021,258.0,18803.437185,28779.971299,264.980379,2462.698252,7001.419123,22009.595072,223823.363960
2022,257.0,19476.548373,28996.961493,302.992505,2536.400502,7606.237525,24387.038729,226052.001905
2023,251.0,20172.185789,30917.462749,250.627253,2541.703814,7802.824333,23979.291930,256799.788613
2024,240.0,19724.631062,30040.258015,219.424831,2619.263802,7836.504782,24745.502555,288001.433369

## Thống kê mô tả cho các cột phân loại

Cell này dùng `describe(include="all")` cho các cột categorical.

Thông tin này giúp xác định:
- cột nào có nhiều giá trị khác nhau,
- giá trị xuất hiện nhiều nhất (`top`),
- tần suất xuất hiện của giá trị phổ biến nhất (`freq`).

Đây là bước hữu ích để kiểm tra xem các cột metadata có hợp lý hay không.

In [9]:
gdp_df[categorical_cols].describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country Name,266,266,Aruba,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country Code,266,266,ABW,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Name,266,1,GDP per capita (current US$),266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Code,266,1,NY.GDP.PCAP.CD,266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 69,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
unnamed_cols = [col for col in gdp_df.columns if str(col).startswith("Unnamed")]

print("Technical / junk columns:")
print(unnamed_cols if unnamed_cols else "No unnamed columns found")

Technical / junk columns:
['Unnamed: 69']

## Phân biệt country rows và aggregate rows

Cell này dùng `Country Code` để tách:
- các dòng đại diện cho quốc gia hoặc lãnh thổ thật,
- các dòng aggregate như khu vực, nhóm thu nhập hoặc nhóm kinh tế.

Điều này rất quan trọng vì dataset WDI không chỉ chứa dữ liệu của từng nước, mà còn chứa nhiều dòng tổng hợp.  
Nếu không tách riêng, kết quả phân tích có thể bị sai lệch.

In [11]:
SPECIAL_COUNTRY_CODES = {"XKX", "SXM"}

def is_country_code(code):
    code = str(code).strip()
    if code in SPECIAL_COUNTRY_CODES:
        return True
    try:
        alpha2 = pc.country_alpha3_to_country_alpha2(code)
        pc.country_alpha2_to_continent_code(alpha2)
        return True
    except:
        return False

country_mask = gdp_df["Country Code"].astype(str).apply(is_country_code)

print("Country / territory rows:", int(country_mask.sum()))
print("Aggregate rows:", int((~country_mask).sum()))

Country / territory rows: 215
Aggregate rows: 51

## Xem danh sách aggregate codes

Cell này liệt kê các mã không phải country thật, tức là các `aggregate codes`.

Mục đích:
- xác định rõ dataset đang chứa những nhóm tổng hợp nào,
- hỗ trợ giải thích tại sao số dòng của dataset lớn hơn số lượng quốc gia thực tế,
- làm cơ sở để loại bỏ aggregate rows khi chỉ muốn phân tích ở cấp quốc gia.

In [12]:
aggregate_codes = gdp_df.loc[~country_mask, "Country Code"].astype(str).unique().tolist()

print("Aggregate codes:")
print(aggregate_codes)

Aggregate codes:
['AFE', 'AFW', 'ARB', 'CEB', 'CHI', 'CSS', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FCS', 'HIC', 'HPC', 'IBD', 'IBT', 'IDA', 'IDB', 'IDX', 'INX', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'LTE', 'MEA', 'MIC', 'MNA', 'NAC', 'OED', 'OSS', 'PRE', 'PSS', 'PST', 'SAS', 'SSA', 'SSF', 'SST', 'TEA', 'TEC', 'TLA', 'TLS', 'TMN', 'TSA', 'TSS', 'UMC', 'WLD']

## Kiểm tra duplicate rows

Cell này kiểm tra xem dataset có dòng nào bị lặp hoàn toàn hay không.

Nếu có duplicate rows, dữ liệu có thể bị:
- ghi trùng,
- merge sai,
- hoặc export lỗi.

In [13]:
print("Duplicate rows:", int(gdp_df.duplicated().sum()))

Duplicate rows: 0

## Kiểm tra `Indicator Name` và `Indicator Code`

Cell này dùng để xác nhận dataset có đúng là chỉ chứa 1 chỉ số duy nhất hay không.

Đối với file `gdp.csv`, kỳ vọng là:
- `Indicator Name` chỉ có 1 giá trị là `GDP per capita (current US$)`,
- `Indicator Code` chỉ có 1 giá trị tương ứng.

In [14]:
print("Indicator Name nunique:", gdp_df["Indicator Name"].nunique())
print("Indicator Code nunique:", gdp_df["Indicator Code"].nunique())

print("\nIndicator Name values:")
print(gdp_df["Indicator Name"].unique())

print("\nIndicator Code values:")
print(gdp_df["Indicator Code"].unique())

Indicator Name nunique: 1
Indicator Code nunique: 1

Indicator Name values:
<StringArray>
['GDP per capita (current US$)']
Length: 1, dtype: str

Indicator Code values:
<StringArray>
['NY.GDP.PCAP.CD']
Length: 1, dtype: str

## Kiểm tra độ đầy đủ dữ liệu theo từng năm

Cell này tính số lượng dòng có dữ liệu ở mỗi cột năm.

Output cho biết:
- năm nào có coverage cao,
- năm nào bị thiếu dữ liệu,
- tỷ lệ hoàn chỉnh dữ liệu theo từng năm.

Đây là bước quan trọng để xác định mức độ đầy đủ dữ liệu của GDP qua thời gian.

In [21]:
year_non_null = gdp_df[numerical_cols].notna().sum().sort_index()

coverage_df = pd.DataFrame({
    "Year": year_non_null.index,
    "non_null_count": year_non_null.values,
    "non_null_ratio_pct": (year_non_null.values / len(gdp_df) * 100).round(2)
})

coverage_df.tail(50)

    Year  non_null_count  non_null_ratio_pct
15  1975             195               73.31
16  1976             195               73.31
17  1977             198               74.44
18  1978             197               74.06
19  1979             198               74.44
20  1980             208               78.20
21  1981             208               78.20
22  1982             209               78.57
23  1983             209               78.57
24  1984             211               79.32
25  1985             213               80.08
26  1986             213               80.08
27  1987             220               82.71
28  1988             223               83.83
29  1989             223               83.83
30  1990             240               90.23
31  1991             241               90.60
32  1992             242               90.98
33  1993             243               91.35
34  1994             244               91.73
35  1995             247               92.86
36  1996             247               92.86
37  1997             249               93.61
38  1998             250               93.98
39  1999             250               93.98
40  2000             252               94.74
41  2001             253               95.11
42  2002             257               96.62
43  2003             257               96.62
44  2004             257               96.62
45  2005             257               96.62
46  2006             258               96.99
47  2007             258               96.99
48  2008             259               97.37
49  2009             261               98.12
50  2010             261               98.12
51  2011             262               98.50
52  2012             260               97.74
53  2013             260               97.74
54  2014             261               98.12
55  2015             260               97.74
56  2016             259               97.37
57  2017             259               97.37
58  2018             259               97.37
59  2019             259               97.37
60  2020             258               96.99
61  2021             258               96.99
62  2022             257               96.62
63  2023             251               94.36
64  2024             240               90.23

In [22]:
latest_year_with_data = coverage_df.loc[coverage_df["non_null_count"] > 0, "Year"].iloc[-1]

print("Latest year with any data:", latest_year_with_data)
print("Non-null rows in latest year:", int(gdp_df[latest_year_with_data].notna().sum()))

Latest year with any data: 2024
Non-null rows in latest year: 240

## Tổng hợp các data issues của GDP dataset

Cell này tổng hợp các vấn đề chính của dataset dưới dạng nhận xét tự động.

Các issue được kiểm tra gồm:
- có cột rác hay không,
- có aggregate rows hay không,
- dataset có chứa đúng 1 indicator duy nhất không,
- có duplicate rows không,
- có cột nào null 100% không,
- có năm nào missing quá cao không,
- cột năm mới nhất có đủ dữ liệu không,
- phân phối dữ liệu có bị lệch mạnh hay không,
- dữ liệu đang ở wide format hay long format.

In [23]:
issues = []

if unnamed_cols:
    issues.append(f"Co cot rac/technical column: {unnamed_cols}")

if (~country_mask).sum() > 0:
    issues.append(
        f"Dataset chua ca aggregate rows, khong chi country rows: {(~country_mask).sum()} dong aggregate, {country_mask.sum()} dong country/territory."
    )

if gdp_df["Indicator Name"].nunique() == 1 and gdp_df["Indicator Code"].nunique() == 1:
    issues.append("File chi chua 1 indicator duy nhat la GDP per capita (current US$).")

if gdp_df.duplicated().sum() == 0:
    issues.append("Khong co duplicate row hoan toan trung nhau.")
else:
    issues.append(f"Co {gdp_df.duplicated().sum()} duplicate rows.")

all_null_cols = gdp_null.loc[gdp_null["null_count"] == len(gdp_df), "column"].tolist()
if all_null_cols:
    issues.append(f"Co cot nam bi null 100%: {all_null_cols}")
else:
    issues.append("Khong co cot nao bi null 100%.")

high_missing_cols = gdp_null.loc[
    (gdp_null["column"].isin(numerical_cols)) & (gdp_null["null_ratio_pct"] >= 30),
    "column"
].tolist()

if high_missing_cols:
    issues.append(f"Cac nam co missing rat cao (>=30%): {high_missing_cols}")
else:
    issues.append("Khong co cot nam nao missing tu 30% tro len.")

count_2024 = int(gdp_df["2024"].notna().sum())
issues.append(f"Cot 2024 chua day du, hien co {count_2024}/{len(gdp_df)} dong co du lieu.")

latest_series = pd.to_numeric(gdp_df[latest_year_with_data], errors="coerce").dropna()
mean_val = latest_series.mean()
median_val = latest_series.median()

if median_val != 0 and mean_val / median_val >= 2:
    issues.append(
        f"Phan phoi GDP lech phai rat manh/outlier cao vi mean ({mean_val:,.2f}) lon hon median ({median_val:,.2f}) rat nhieu."
    )

issues.append("Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.")

for i, issue in enumerate(issues, start=1):
    print(f"{i}. {issue}")

1. Co cot rac/technical column: ['Unnamed: 69']
2. Dataset chua ca aggregate rows, khong chi country rows: 51 dong aggregate, 215 dong country/territory.
3. File chi chua 1 indicator duy nhat la GDP per capita (current US$).
4. Khong co duplicate row hoan toan trung nhau.
5. Co cot nam bi null 100%: ['Unnamed: 69']
6. Cac nam co missing rat cao (>=30%): ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969']
7. Cot 2024 chua day du, hien co 240/266 dong co du lieu.
8. Phan phoi GDP lech phai rat manh/outlier cao vi mean (19,724.63) lon hon median (7,836.50) rat nhieu.
9. Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.

In [26]:
coverage_df.sort_values("non_null_count").head(10)

   Year  non_null_count  non_null_ratio_pct
0  1960             151               56.77
1  1961             154               57.89
2  1962             156               58.65
3  1963             156               58.65
4  1964             156               58.65
5  1965             162               60.90
6  1966             163               61.28
7  1967             167               62.78
8  1968             168               63.16
9  1969             168               63.16