In [1]:
import pandas as pd
import pycountry_convert as pc

LIFE_PATH = "/Users/tonytony/life_expectancy.csv"

life_df = pd.read_csv(LIFE_PATH, skiprows=4)
print("Shape:", life_df.shape)
life_df.head()

Shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.049000,64.215000,64.602000,64.944000,65.303000,65.615000,...,75.540000,75.620000,75.880000,76.019000,75.406000,73.655000,76.226000,76.353000,NaN,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.169658,44.468838,44.877890,45.160583,45.535695,45.770723,...,62.167981,62.591275,63.330691,63.857261,63.766484,62.979999,64.487020,65.146154,NaN,NaN
2,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.799000,33.291000,33.757000,34.201000,34.673000,35.124000,...,62.646000,62.406000,62.443000,62.941000,61.454000,60.417000,65.617000,66.035000,NaN,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.779636,38.058956,38.681792,38.936918,39.194580,39.479784,...,56.392452,56.626439,57.036976,57.149847,57.364425,57.362572,57.987813,58.855722,NaN,NaN
4,Angola,AGO,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.933000,36.902000,37.168000,37.419000,37.704000,37.968000,...,61.619000,62.122000,62.622000,63.051000,63.116000,62.958000,64.246000,64.617000,NaN,NaN

## Kiểm tra cấu trúc bằng `df.info()`

Cell này dùng để xem tổng quan cấu trúc dữ liệu của `Life Expectancy dataset`.

Thông tin quan trọng từ `df.info()` gồm:
- tổng số dòng,
- tổng số cột,
- tên các cột,
- kiểu dữ liệu của từng cột,
- số lượng giá trị non-null của mỗi cột.

Kết quả này giúp xác định:
- cột nào là text, cột nào là số,
- cột nào có nhiều giá trị thiếu,
- có cột bất thường hay không.

In [2]:
life_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            263 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            263 non-null    float64
 8   1964            263 non-null    float64
 9   1965            263 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            0 non-null      float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB

## Kiểm tra số dòng, số cột và danh sách cột

Cell này in ra:
- số dòng của dataset,
- số cột của dataset,
- toàn bộ tên cột hiện có.

Mục tiêu của bước này là xác nhận trực tiếp cấu trúc bảng dữ liệu, đặc biệt hữu ích với dữ liệu WDI vì dataset thường gồm:
- các cột metadata như `Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`,
- các cột năm từ `1960` đến `2024`,
- và đôi khi có thêm cột rác như `Unnamed: 69`.

In [3]:
print("Number of rows:", life_df.shape[0])
print("Number of columns:", life_df.shape[1])
print("\nColumns:")
print(life_df.columns.tolist())

Number of rows: 266
Number of columns: 70

Columns:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', 'Unnamed: 69']

## Phân loại cột numerical và categorical

Cell này chia các cột thành 2 nhóm chính:
- `numerical columns`: các cột năm như `1960`, `1961`, ..., `2024`,
- `categorical columns`: các cột mô tả như `Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`.

Vai trò:
- nhóm numerical sẽ được dùng cho thống kê mô tả, missing values và visualization,
- nhóm categorical sẽ được dùng để nhận diện quốc gia, mã nước và metadata của dataset.

In [4]:
numerical_cols = [col for col in life_df.columns if str(col).isdigit()]
categorical_cols = [col for col in life_df.columns if col not in numerical_cols]

print("Numerical columns:", len(numerical_cols))
print(numerical_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

Numerical columns: 65
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

Categorical columns: 5
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 69']

## Kiểm tra số lượng giá trị duy nhất bằng `nunique()`

Cell này tính số lượng giá trị duy nhất của từng cột.

Bước này giúp trả lời các câu hỏi như:
- có bao nhiêu quốc gia hoặc vùng khác nhau trong dataset,
- `Indicator Name` có bao nhiêu loại,
- `Indicator Code` có bao nhiêu loại,
- các cột năm có bao nhiêu giá trị khác nhau.

Kết quả `nunique()` rất hữu ích để phát hiện:
- cột chỉ chứa 1 giá trị lặp đi lặp lại,
- cột có tính phân biệt cao như mã quốc gia,
- hoặc các cột không mang nhiều thông tin.

In [5]:
life_nunique = pd.DataFrame({
    "column": life_df.columns,
    "dtype": life_df.dtypes.astype(str).values,
    "nunique": [life_df[col].nunique(dropna=True) for col in life_df.columns]
})

life_nunique

            column    dtype  nunique
0     Country Name      str      266
1     Country Code      str      266
2   Indicator Name      str        1
3   Indicator Code      str        1
4             1960  float64      259
..             ...      ...      ...
65            2021  float64      262
66            2022  float64      261
67            2023  float64      263
68            2024  float64        0
69     Unnamed: 69  float64        0

[70 rows x 3 columns]

## Kiểm tra số lượng giá trị thiếu

Cell này tạo bảng tóm tắt missing values cho từng cột, bao gồm:
- `null_count`: số lượng giá trị thiếu,
- `null_ratio_pct`: tỷ lệ phần trăm giá trị thiếu,
- `dtype`: kiểu dữ liệu của cột.

Đây là bước quan trọng để đánh giá chất lượng dữ liệu.  
Với Life Expectancy, bước này đặc biệt hữu ích để phát hiện xem cột năm mới nhất có dữ liệu hay chưa.

In [6]:
life_null = pd.DataFrame({
    "column": life_df.columns,
    "null_count": life_df.isnull().sum().values,
    "null_ratio_pct": (life_df.isnull().mean() * 100).round(2).values,
    "dtype": life_df.dtypes.astype(str).values
}).sort_values(["null_count", "column"], ascending=[False, True])

life_null

            column  null_count  null_ratio_pct    dtype
68            2024         266          100.00  float64
69     Unnamed: 69         266          100.00  float64
4             1960           3            1.13  float64
7             1963           3            1.13  float64
8             1964           3            1.13  float64
..             ...         ...             ...      ...
67            2023           1            0.38  float64
1     Country Code           0            0.00      str
0     Country Name           0            0.00      str
3   Indicator Code           0            0.00      str
2   Indicator Name           0            0.00      str

[70 rows x 4 columns]

In [7]:
life_null.head(15)

         column  null_count  null_ratio_pct    dtype
68         2024         266          100.00  float64
69  Unnamed: 69         266          100.00  float64
4          1960           3            1.13  float64
7          1963           3            1.13  float64
8          1964           3            1.13  float64
9          1965           3            1.13  float64
5          1961           2            0.75  float64
6          1962           2            0.75  float64
10         1966           2            0.75  float64
11         1967           2            0.75  float64
12         1968           2            0.75  float64
13         1969           2            0.75  float64
14         1970           2            0.75  float64
15         1971           2            0.75  float64
16         1972           2            0.75  float64

## Thống kê mô tả cho các cột số bằng `describe()`

Cell này áp dụng `describe()` cho toàn bộ các cột numerical, tức là các cột năm.

Kết quả bao gồm:
- `count`: số lượng giá trị hợp lệ,
- `mean`: giá trị trung bình,
- `std`: độ lệch chuẩn,
- `min`: giá trị nhỏ nhất,
- `25%`, `50%`, `75%`: các phân vị,
- `max`: giá trị lớn nhất.

Bảng này giúp đánh giá nhanh phân phối Life Expectancy theo từng năm và so sánh mức độ phân tán dữ liệu.

In [8]:
life_df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
1960,263.0,54.021422,11.615002,28.054,43.568100,54.359000,64.195500,74.040073
1961,264.0,54.664230,11.454925,28.278,44.831894,54.730500,64.731500,73.652683
1962,264.0,55.280667,11.144828,28.506,45.957827,55.346515,64.954006,73.721951
1963,263.0,55.606368,11.076024,28.249,46.475500,55.711419,65.245171,73.586000
1964,263.0,56.102078,11.004538,31.231,47.065000,56.220000,65.657037,73.855927
...,...,...,...,...,...,...,...,...
2020,265.0,72.144870,7.226410,50.596,66.924000,72.636000,77.449810,86.089000
2021,265.0,71.430551,7.481863,40.279,66.199000,71.757000,76.865768,85.532683
2022,265.0,72.795654,7.648548,18.818,67.713000,73.702439,77.832768,85.746000
2023,265.0,73.458600,6.960836,54.462,68.337000,73.844000,78.473171,86.372000
2024,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Thống kê mô tả cho các cột phân loại

Cell này dùng `describe(include="all")` cho các cột categorical.

Thông tin này giúp xác định:
- cột nào có nhiều giá trị khác nhau,
- giá trị xuất hiện nhiều nhất (`top`),
- tần suất xuất hiện của giá trị phổ biến nhất (`freq`).

Đây là bước hữu ích để kiểm tra tính hợp lý của các cột metadata.

In [9]:
life_df[categorical_cols].describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country Name,266,266,Aruba,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country Code,266,266,ABW,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Name,266,1,"Life expectancy at birth, total (years)",266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Code,266,1,SP.DYN.LE00.IN,266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 69,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
unnamed_cols = [col for col in life_df.columns if str(col).startswith("Unnamed")]

print("Technical / junk columns:")
print(unnamed_cols if unnamed_cols else "No unnamed columns found")

Technical / junk columns:
['Unnamed: 69']

## Phân biệt country rows và aggregate rows

Cell này dùng `Country Code` để tách:
- các dòng đại diện cho quốc gia hoặc lãnh thổ thật,
- các dòng aggregate như khu vực, nhóm thu nhập hoặc nhóm kinh tế.

Điều này rất quan trọng vì dataset WDI không chỉ chứa dữ liệu của từng nước, mà còn chứa nhiều dòng tổng hợp.  
Nếu không tách riêng, kết quả phân tích có thể bị sai lệch.

In [11]:
SPECIAL_COUNTRY_CODES = {"XKX", "SXM"}

def is_country_code(code):
    code = str(code).strip()
    if code in SPECIAL_COUNTRY_CODES:
        return True
    try:
        alpha2 = pc.country_alpha3_to_country_alpha2(code)
        pc.country_alpha2_to_continent_code(alpha2)
        return True
    except:
        return False

country_mask = life_df["Country Code"].astype(str).apply(is_country_code)

print("Country / territory rows:", int(country_mask.sum()))
print("Aggregate rows:", int((~country_mask).sum()))

Country / territory rows: 215
Aggregate rows: 51

In [12]:
aggregate_codes = life_df.loc[~country_mask, "Country Code"].astype(str).unique().tolist()

print("Aggregate codes:")
print(aggregate_codes)

Aggregate codes:
['AFE', 'AFW', 'ARB', 'CEB', 'CHI', 'CSS', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FCS', 'HIC', 'HPC', 'IBD', 'IBT', 'IDA', 'IDB', 'IDX', 'INX', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'LTE', 'MEA', 'MIC', 'MNA', 'NAC', 'OED', 'OSS', 'PRE', 'PSS', 'PST', 'SAS', 'SSA', 'SSF', 'SST', 'TEA', 'TEC', 'TLA', 'TLS', 'TMN', 'TSA', 'TSS', 'UMC', 'WLD']

In [13]:
print("Duplicate rows:", int(life_df.duplicated().sum()))

Duplicate rows: 0

## Kiểm tra `Indicator Name` và `Indicator Code`

Cell này dùng để xác nhận dataset có đúng là chỉ chứa 1 chỉ số duy nhất hay không.

Đối với file `life_expectancy.csv`, kỳ vọng là:
- `Indicator Name` chỉ có 1 giá trị là `Life expectancy at birth, total (years)`,
- `Indicator Code` chỉ có 1 giá trị tương ứng.

Điều này cho thấy file hiện tại là một dataset đơn biến theo thời gian.

In [14]:
print("Indicator Name nunique:", life_df["Indicator Name"].nunique())
print("Indicator Code nunique:", life_df["Indicator Code"].nunique())

print("\nIndicator Name values:")
print(life_df["Indicator Name"].unique())

print("\nIndicator Code values:")
print(life_df["Indicator Code"].unique())

Indicator Name nunique: 1
Indicator Code nunique: 1

Indicator Name values:
<StringArray>
['Life expectancy at birth, total (years)']
Length: 1, dtype: str

Indicator Code values:
<StringArray>
['SP.DYN.LE00.IN']
Length: 1, dtype: str

## 15. Kiểm tra độ đầy đủ dữ liệu theo từng năm

Cell này tính số lượng dòng có dữ liệu ở mỗi cột năm.

Output cho biết:
- năm nào có coverage cao,
- năm nào bị thiếu dữ liệu,
- tỷ lệ hoàn chỉnh dữ liệu theo từng năm.

Đây là bước quan trọng để xác định mức độ đầy đủ dữ liệu của Life Expectancy qua thời gian.

In [15]:
year_non_null = life_df[numerical_cols].notna().sum().sort_index()

coverage_df = pd.DataFrame({
    "Year": year_non_null.index,
    "non_null_count": year_non_null.values,
    "non_null_ratio_pct": (year_non_null.values / len(life_df) * 100).round(2)
})

coverage_df.tail(15)

    Year  non_null_count  non_null_ratio_pct
50  2010             265               99.62
51  2011             265               99.62
52  2012             265               99.62
53  2013             265               99.62
54  2014             265               99.62
55  2015             265               99.62
56  2016             265               99.62
57  2017             265               99.62
58  2018             265               99.62
59  2019             265               99.62
60  2020             265               99.62
61  2021             265               99.62
62  2022             265               99.62
63  2023             265               99.62
64  2024               0                0.00

In [16]:
latest_year_with_data = coverage_df.loc[coverage_df["non_null_count"] > 0, "Year"].iloc[-1]

print("Latest year with any data:", latest_year_with_data)
print("Non-null rows in latest year:", int(life_df[latest_year_with_data].notna().sum()))

Latest year with any data: 2023
Non-null rows in latest year: 265

## Tổng hợp các data issues của Life Expectancy dataset

Cell này tổng hợp các vấn đề chính của dataset dưới dạng nhận xét tự động.

Các issue được kiểm tra gồm:
- có cột rác hay không,
- có aggregate rows hay không,
- dataset có chứa đúng 1 indicator duy nhất không,
- có duplicate rows không,
- có cột nào null 100% không,
- có năm nào missing quá cao không,
- cột năm mới nhất có đủ dữ liệu không,
- dữ liệu đang ở wide format hay long format.

In [17]:
issues = []

if unnamed_cols:
    issues.append(f"Co cot rac/technical column: {unnamed_cols}")

if (~country_mask).sum() > 0:
    issues.append(
        f"Dataset chua ca aggregate rows, khong chi country rows: {(~country_mask).sum()} dong aggregate, {country_mask.sum()} dong country/territory."
    )

if life_df["Indicator Name"].nunique() == 1 and life_df["Indicator Code"].nunique() == 1:
    issues.append("File chi chua 1 indicator duy nhat la Life expectancy at birth, total (years).")

if life_df.duplicated().sum() == 0:
    issues.append("Khong co duplicate row hoan toan trung nhau.")
else:
    issues.append(f"Co {life_df.duplicated().sum()} duplicate rows.")

all_null_cols = life_null.loc[life_null["null_count"] == len(life_df), "column"].tolist()
if all_null_cols:
    issues.append(f"Co cot nam bi null 100%: {all_null_cols}")
else:
    issues.append("Khong co cot nao bi null 100%.")

high_missing_cols = life_null.loc[
    (life_null["column"].isin(numerical_cols)) & (life_null["null_ratio_pct"] >= 30),
    "column"
].tolist()

if high_missing_cols:
    issues.append(f"Cac nam co missing rat cao (>=30%): {high_missing_cols}")
else:
    issues.append("Khong co cot nam nao missing tu 30% tro len.")

count_2024 = int(life_df["2024"].notna().sum())
if count_2024 == 0:
    issues.append("Cot 2024 null 100%, vi vay khong the dung 2024 cho phan tich.")
else:
    issues.append(f"Cot 2024 co {count_2024}/{len(life_df)} dong co du lieu.")

issues.append(f"Nam moi nhat co du lieu thuc su la {latest_year_with_data}.")
issues.append("Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.")

for i, issue in enumerate(issues, start=1):
    print(f"{i}. {issue}")

1. Co cot rac/technical column: ['Unnamed: 69']
2. Dataset chua ca aggregate rows, khong chi country rows: 51 dong aggregate, 215 dong country/territory.
3. File chi chua 1 indicator duy nhat la Life expectancy at birth, total (years).
4. Khong co duplicate row hoan toan trung nhau.
5. Co cot nam bi null 100%: ['2024', 'Unnamed: 69']
6. Cac nam co missing rat cao (>=30%): ['2024']
7. Cot 2024 null 100%, vi vay khong the dung 2024 cho phan tich.
8. Nam moi nhat co du lieu thuc su la 2023.
9. Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.

In [18]:
coverage_df.sort_values("non_null_count").head(10)

    Year  non_null_count  non_null_ratio_pct
64  2024               0                0.00
5   1965             263               98.87
4   1964             263               98.87
0   1960             263               98.87
3   1963             263               98.87
2   1962             264               99.25
29  1989             264               99.25
28  1988             264               99.25
27  1987             264               99.25
26  1986             264               99.25