In [21]:
import pandas as pd
import pycountry_convert as pc

POP_PATH = "/Users/tonytony/population.csv"

pop_df = pd.read_csv(POP_PATH, skiprows=4)

print("Shape:", pop_df.shape)
pop_df.head()

Shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

In [4]:
pop_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB

In [5]:
print("Number of rows:", pop_df.shape[0])
print("Number of columns:", pop_df.shape[1])
print("\nColumns:")
print(pop_df.columns.tolist())

Number of rows: 266
Number of columns: 70

Columns:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', 'Unnamed: 69']

In [6]:
numerical_cols = [col for col in pop_df.columns if str(col).isdigit()]
categorical_cols = [col for col in pop_df.columns if col not in numerical_cols]

print("Numerical columns:", len(numerical_cols))
print(numerical_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

Numerical columns: 65
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

Categorical columns: 5
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 69']

## Phân loại cột numerical và categorical

Cell này chia các cột thành 2 nhóm chính:
- `numerical columns`: các cột năm như `1960`, `1961`, ..., `2024`,
- `categorical columns`: các cột mô tả như `Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`.

Việc phân loại này quan trọng vì:
- nhóm numerical sẽ được dùng cho thống kê mô tả, missing values và visualization,
- nhóm categorical sẽ được dùng để nhận diện quốc gia, mã nước và metadata của dataset.

In [7]:
pop_nunique = pd.DataFrame({
    "column": pop_df.columns,
    "dtype": pop_df.dtypes.astype(str).values,
    "nunique": [pop_df[col].nunique(dropna=True) for col in pop_df.columns]
})

pop_nunique

            column    dtype  nunique
0     Country Name      str      266
1     Country Code      str      266
2   Indicator Name      str        1
3   Indicator Code      str        1
4             1960  float64      260
..             ...      ...      ...
65            2021  float64      263
66            2022  float64      263
67            2023  float64      263
68            2024  float64      263
69     Unnamed: 69  float64        0

[70 rows x 3 columns]

## Kiểm tra số lượng giá trị duy nhất bằng `nunique()`

Cell này tính số lượng giá trị duy nhất của từng cột.

Bước này giúp trả lời các câu hỏi như:
- có bao nhiêu quốc gia hoặc vùng khác nhau trong dataset,
- `Indicator Name` có bao nhiêu loại,
- `Indicator Code` có bao nhiêu loại,
- các cột năm có bao nhiêu giá trị khác nhau.

Kết quả `nunique()` rất hữu ích để phát hiện:
- cột chỉ chứa 1 giá trị lặp đi lặp lại,
- cột có tính phân biệt cao như mã quốc gia,
- hoặc các cột không mang nhiều thông tin.

In [8]:
pop_null = pd.DataFrame({
    "column": pop_df.columns,
    "null_count": pop_df.isnull().sum().values,
    "null_ratio_pct": (pop_df.isnull().mean() * 100).round(2).values,
    "dtype": pop_df.dtypes.astype(str).values
}).sort_values(["null_count", "column"], ascending=[False, True])

pop_null

            column  null_count  null_ratio_pct    dtype
69     Unnamed: 69         266          100.00  float64
4             1960           2            0.75  float64
5             1961           2            0.75  float64
6             1962           2            0.75  float64
7             1963           2            0.75  float64
..             ...         ...             ...      ...
68            2024           1            0.38  float64
1     Country Code           0            0.00      str
0     Country Name           0            0.00      str
3   Indicator Code           0            0.00      str
2   Indicator Name           0            0.00      str

[70 rows x 4 columns]

## Kiểm tra số lượng giá trị thiếu

Cell này tạo bảng tóm tắt missing values cho từng cột, bao gồm:
- `null_count`: số lượng giá trị thiếu,
- `null_ratio_pct`: tỷ lệ phần trăm giá trị thiếu,
- `dtype`: kiểu dữ liệu của cột.

Đây là bước quan trọng để đánh giá chất lượng dữ liệu.  
Nếu một cột có tỷ lệ thiếu cao, đặc biệt là các cột năm gần nhất hoặc lâu nhất, thì cần lưu ý khi phân tích và trực quan hóa.

In [9]:
pop_null.head(15)

         column  null_count  null_ratio_pct    dtype
69  Unnamed: 69         266          100.00  float64
4          1960           2            0.75  float64
5          1961           2            0.75  float64
6          1962           2            0.75  float64
7          1963           2            0.75  float64
8          1964           2            0.75  float64
9          1965           2            0.75  float64
10         1966           2            0.75  float64
11         1967           2            0.75  float64
12         1968           2            0.75  float64
13         1969           2            0.75  float64
14         1970           2            0.75  float64
15         1971           2            0.75  float64
16         1972           2            0.75  float64
17         1973           2            0.75  float64

## Xem các cột thiếu dữ liệu nhiều nhất

Cell này hiển thị các cột có số lượng missing values cao nhất.

Mục tiêu là:
- xác định nhanh cột nào đang có vấn đề về độ đầy đủ dữ liệu,
- xem các năm nào bị thiếu nhiều hơn so với các năm khác,
- chuẩn bị cho phần nhận xét về chất lượng dữ liệu.

Với dữ liệu theo thời gian, các năm đầu hoặc năm rất mới thường có thể thiếu dữ liệu nhiều hơn.

In [10]:
pop_df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
1960,264.0,1.153986e+08,3.616512e+08,2715.0,515202.75,3659633.0,26862930.00,3.021513e+09
1961,264.0,1.170032e+08,3.661333e+08,2970.0,525523.00,3747132.5,27613257.00,3.062768e+09
1962,264.0,1.191639e+08,3.727667e+08,3264.0,536301.75,3831900.0,28373019.75,3.117372e+09
1963,264.0,1.218340e+08,3.813673e+08,3584.0,547587.50,3919709.5,29154482.25,3.184063e+09
1964,264.0,1.245281e+08,3.900147e+08,3922.0,559363.75,4010150.5,29952226.75,3.251253e+09
...,...,...,...,...,...,...,...,...
2020,265.0,3.187768e+08,9.865558e+08,10399.0,1790151.00,10697858.0,60972798.00,7.854748e+09
2021,265.0,3.219350e+08,9.952478e+08,10194.0,1786079.00,10505772.0,62830412.00,7.920515e+09
2022,265.0,3.250893e+08,1.003664e+09,9992.0,1803545.00,10486941.0,64711821.00,7.989545e+09
2023,265.0,3.283978e+08,1.012445e+09,9816.0,1827816.00,10644851.0,66617606.00,8.064058e+09
2024,265.0,3.318713e+08,1.021698e+09,9646.0,1824359.00,10905028.0,68551653.00,8.141809e+09

## Thống kê mô tả cho các cột số bằng `describe()`

Cell này áp dụng `describe()` cho toàn bộ các cột numerical, tức là các cột năm.

Kết quả bao gồm:
- `count`: số lượng giá trị hợp lệ,
- `mean`: giá trị trung bình,
- `std`: độ lệch chuẩn,
- `min`: giá trị nhỏ nhất,
- `25%`, `50%`, `75%`: các phân vị,
- `max`: giá trị lớn nhất.

Bảng này giúp đánh giá nhanh phân phối population theo từng năm và phát hiện khả năng có outlier lớn.

In [11]:
pop_df[categorical_cols].describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country Name,266,266,Aruba,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country Code,266,266,ABW,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Name,266,1,"Population, total",266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator Code,266,1,SP.POP.TOTL,266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 69,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Thống kê mô tả cho các cột phân loại

Cell này dùng `describe(include="all")` cho các cột categorical.

Thông tin này giúp xác định:
- cột nào có nhiều giá trị khác nhau,
- giá trị xuất hiện nhiều nhất (`top`),
- tần suất xuất hiện của giá trị phổ biến nhất (`freq`).

Đây là bước hữu ích để kiểm tra xem các cột metadata có hợp lý hay không, đặc biệt là:
- `Country Name`,
- `Country Code`,
- `Indicator Name`,
- `Indicator Code`.

In [12]:
unnamed_cols = [col for col in pop_df.columns if str(col).startswith("Unnamed")]

print("Technical / junk columns:")
print(unnamed_cols if unnamed_cols else "No unnamed columns found")

Technical / junk columns:
['Unnamed: 69']

In [13]:
SPECIAL_COUNTRY_CODES = {"XKX", "SXM"}

def is_country_code(code):
    code = str(code).strip()
    if code in SPECIAL_COUNTRY_CODES:
        return True
    try:
        alpha2 = pc.country_alpha3_to_country_alpha2(code)
        pc.country_alpha2_to_continent_code(alpha2)
        return True
    except:
        return False

country_mask = pop_df["Country Code"].astype(str).apply(is_country_code)

print("Country / territory rows:", int(country_mask.sum()))
print("Aggregate rows:", int((~country_mask).sum()))

Country / territory rows: 215
Aggregate rows: 51

## Phân biệt country rows và aggregate rows

Cell này dùng `Country Code` để tách:
- các dòng đại diện cho quốc gia hoặc lãnh thổ thật,
- các dòng aggregate như khu vực, nhóm thu nhập hoặc nhóm kinh tế.

Điều này rất quan trọng vì dataset WDI không chỉ chứa dữ liệu của từng nước, mà còn chứa:
- `WLD`,
- `EAS`,
- `SAS`,
- `LMY`,
- và nhiều mã nhóm khác.

Nếu không tách riêng, kết quả phân tích có thể bị sai lệch.

In [14]:
aggregate_codes = pop_df.loc[~country_mask, "Country Code"].astype(str).unique().tolist()

print("Aggregate codes:")
print(aggregate_codes)

Aggregate codes:
['AFE', 'AFW', 'ARB', 'CEB', 'CHI', 'CSS', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FCS', 'HIC', 'HPC', 'IBD', 'IBT', 'IDA', 'IDB', 'IDX', 'INX', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'LTE', 'MEA', 'MIC', 'MNA', 'NAC', 'OED', 'OSS', 'PRE', 'PSS', 'PST', 'SAS', 'SSA', 'SSF', 'SST', 'TEA', 'TEC', 'TLA', 'TLS', 'TMN', 'TSA', 'TSS', 'UMC', 'WLD']

In [15]:
print("Duplicate rows:", int(pop_df.duplicated().sum()))

Duplicate rows: 0

In [16]:
print("Indicator Name nunique:", pop_df["Indicator Name"].nunique())
print("Indicator Code nunique:", pop_df["Indicator Code"].nunique())

print("\nIndicator Name values:")
print(pop_df["Indicator Name"].unique())

print("\nIndicator Code values:")
print(pop_df["Indicator Code"].unique())

Indicator Name nunique: 1
Indicator Code nunique: 1

Indicator Name values:
<StringArray>
['Population, total']
Length: 1, dtype: str

Indicator Code values:
<StringArray>
['SP.POP.TOTL']
Length: 1, dtype: str

## Kiểm tra `Indicator Name` và `Indicator Code`

Cell này dùng để xác nhận dataset có đúng là chỉ chứa 1 chỉ số duy nhất hay không.

Đối với file `population.csv`, kỳ vọng là:
- `Indicator Name` chỉ có 1 giá trị là `Population, total`,
- `Indicator Code` chỉ có 1 giá trị tương ứng.

Điều này cho thấy file hiện tại là một dataset đơn biến theo thời gian, không phải file gộp nhiều chỉ số khác nhau.

In [17]:
year_non_null = pop_df[numerical_cols].notna().sum().sort_index()

coverage_df = pd.DataFrame({
    "Year": year_non_null.index,
    "non_null_count": year_non_null.values,
    "non_null_ratio_pct": (year_non_null.values / len(pop_df) * 100).round(2)
})

coverage_df.tail(15)

    Year  non_null_count  non_null_ratio_pct
50  2010             265               99.62
51  2011             265               99.62
52  2012             265               99.62
53  2013             265               99.62
54  2014             265               99.62
55  2015             265               99.62
56  2016             265               99.62
57  2017             265               99.62
58  2018             265               99.62
59  2019             265               99.62
60  2020             265               99.62
61  2021             265               99.62
62  2022             265               99.62
63  2023             265               99.62
64  2024             265               99.62

## Kiểm tra độ đầy đủ dữ liệu theo từng năm

Cell này tính số lượng dòng có dữ liệu ở mỗi cột năm.

Output cho biết:
- năm nào có coverage cao,
- năm nào bị thiếu dữ liệu,
- tỷ lệ hoàn chỉnh dữ liệu theo từng năm.

Đây là bước quan trọng để xác định:
- năm mới nhất nào đủ tốt để dùng trong phân tích,
- mức độ đầy đủ dữ liệu qua thời gian.

In [18]:
latest_year_with_data = coverage_df.loc[coverage_df["non_null_count"] > 0, "Year"].iloc[-1]

print("Latest year with any data:", latest_year_with_data)
print("Non-null rows in latest year:", int(pop_df[latest_year_with_data].notna().sum()))

Latest year with any data: 2024
Non-null rows in latest year: 265

## Xác định năm mới nhất còn dữ liệu

Cell này tìm năm mới nhất mà dataset vẫn còn giá trị hợp lệ.

Thông tin này rất quan trọng vì:
- không phải lúc nào cột năm cuối cùng cũng có dữ liệu đầy đủ,
- khi làm EDA hoặc vẽ bản đồ, nên chọn năm mới nhất có dữ liệu thực sự.

Kết quả của cell này sẽ được dùng làm mốc cho các bước phân tích tiếp theo.

In [19]:
issues = []

if unnamed_cols:
    issues.append(f"Co cot rac/technical column: {unnamed_cols}")

if (~country_mask).sum() > 0:
    issues.append(
        f"Dataset chua ca aggregate rows, khong chi country rows: {(~country_mask).sum()} dong aggregate, {country_mask.sum()} dong country/territory."
    )

if pop_df["Indicator Name"].nunique() == 1 and pop_df["Indicator Code"].nunique() == 1:
    issues.append("File chi chua 1 indicator duy nhat la Population, total.")

if pop_df.duplicated().sum() == 0:
    issues.append("Khong co duplicate row hoan toan trung nhau.")
else:
    issues.append(f"Co {pop_df.duplicated().sum()} duplicate rows.")

all_null_cols = pop_null.loc[pop_null["null_count"] == len(pop_df), "column"].tolist()
if all_null_cols:
    issues.append(f"Co cot nam bi null 100%: {all_null_cols}")
else:
    issues.append("Khong co cot nao bi null 100%.")

high_missing_cols = pop_null.loc[
    (pop_null["column"].isin(numerical_cols)) & (pop_null["null_ratio_pct"] >= 30),
    "column"
].tolist()

if high_missing_cols:
    issues.append(f"Cac nam co missing rat cao (>=30%): {high_missing_cols}")
else:
    issues.append("Khong co cot nam nao missing tu 30% tro len.")

count_2024 = int(pop_df["2024"].notna().sum())
issues.append(f"Cot 2024 gan nhu day du, co {count_2024}/{len(pop_df)} dong co du lieu.")

latest_series = pd.to_numeric(pop_df[latest_year_with_data], errors="coerce").dropna()
mean_val = latest_series.mean()
median_val = latest_series.median()

if median_val != 0 and mean_val / median_val >= 2:
    issues.append(
        f"Phan phoi population lech phai rat manh/outlier cao vi mean ({mean_val:,.2f}) lon hon median ({median_val:,.2f}) rat nhieu."
    )

issues.append("Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.")

for i, issue in enumerate(issues, start=1):
    print(f"{i}. {issue}")

1. Co cot rac/technical column: ['Unnamed: 69']
2. Dataset chua ca aggregate rows, khong chi country rows: 51 dong aggregate, 215 dong country/territory.
3. File chi chua 1 indicator duy nhat la Population, total.
4. Khong co duplicate row hoan toan trung nhau.
5. Co cot nam bi null 100%: ['Unnamed: 69']
6. Khong co cot nam nao missing tu 30% tro len.
7. Cot 2024 gan nhu day du, co 265/266 dong co du lieu.
8. Phan phoi population lech phai rat manh/outlier cao vi mean (331,871,342.02) lon hon median (10,905,028.00) rat nhieu.
9. Du lieu dang o wide format theo nam, can melt sang long format neu muon phan tich time series hoac merge voi dataset khac.

## Tổng hợp các data issues của Population dataset

Cell này tổng hợp các vấn đề chính của dataset dưới dạng nhận xét tự động.

Các issue được kiểm tra gồm:
- có cột rác hay không,
- có aggregate rows hay không,
- dataset có chứa đúng 1 indicator duy nhất không,
- có duplicate rows không,
- có cột nào null 100% không,
- có năm nào missing quá cao không,
- cột năm mới nhất có đủ dữ liệu không,
- phân phối dữ liệu có bị lệch mạnh hay không,
- dữ liệu đang ở wide format hay long format.

In [20]:
coverage_df.sort_values("non_null_count").head(10)

    Year  non_null_count  non_null_ratio_pct
0   1960             264               99.25
29  1989             264               99.25
28  1988             264               99.25
27  1987             264               99.25
26  1986             264               99.25
25  1985             264               99.25
24  1984             264               99.25
23  1983             264               99.25
21  1981             264               99.25
20  1980             264               99.25

## Xem các năm có độ thiếu dữ liệu cao nhất

Cell này sắp xếp các năm theo số lượng dữ liệu hợp lệ tăng dần để xác định:
- năm nào đang thiếu nhiều dữ liệu nhất,
- mức độ chênh lệch coverage giữa các năm.

Bước này hỗ trợ phần kết luận về chất lượng dữ liệu theo thời gian và giúp quyết định nên chọn năm nào cho phân tích sâu hơn.