In [1]:
import pandas as pd

GDP_PATH = "/Users/tonytony/Final Project/Data/Raw/gdp.csv"
LIFE_PATH = "/Users/tonytony/Final Project/Data/Raw/life_expectancy.csv"
POP_PATH = "/Users/tonytony/Final Project/Data/Raw/population.csv"
META_PATH = "/Users/tonytony/Final Project/Data/Raw/world_bank_country_metadata.csv"
print("GDP:", GDP_PATH)
print("Life:", LIFE_PATH)
print("Population:", POP_PATH)
print("Metadata:", META_PATH)

GDP: /Users/tonytony/Final Project/Data/Raw/gdp.csv
Life: /Users/tonytony/Final Project/Data/Raw/life_expectancy.csv
Population: /Users/tonytony/Final Project/Data/Raw/population.csv
Metadata: /Users/tonytony/Final Project/Data/Raw/world_bank_country_metadata.csv

In [2]:
wb_meta = pd.read_csv(META_PATH)

print("Metadata shape:", wb_meta.shape)
print("Metadata columns:")
print(wb_meta.columns.tolist())

wb_meta.head()

Metadata shape: (296, 10)
Metadata columns:
['Country Code', 'ISO2 Code', 'World Bank Name', 'World Bank Region', 'Admin Region', 'Income Level', 'Lending Type', 'Capital City', 'Longitude', 'Latitude']

,Country Code,ISO2 Code,World Bank Name,World Bank Region,Admin Region,Income Level,Lending Type,Capital City,Longitude,Latitude
0,ABW,AW,Aruba,Latin America & Caribbean,NaN,High income,Not classified,Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,IDA,Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN
4,AFW,ZI,Africa Western and Central,Aggregates,NaN,Aggregates,Aggregates,NaN,NaN,NaN

In [3]:
wb_region_map = wb_meta[[
    "Country Code",
    "World Bank Region",
    "Admin Region",
    "Income Level",
    "Lending Type"
]].drop_duplicates(subset=["Country Code"]).copy()

wb_region_map = wb_region_map.rename(columns={
    "World Bank Region": "WB Region"
})

wb_region_map["Country Type"] = wb_region_map["WB Region"].apply(
    lambda x: "Aggregate" if str(x).strip() == "Aggregates" else "Country/Territory"
)

print("WB region mapping table shape:", wb_region_map.shape)
wb_region_map.head(10)

WB region mapping table shape: (296, 6)

,Country Code,WB Region,Admin Region,Income Level,Lending Type,Country Type
0,ABW,Latin America & Caribbean,NaN,High income,Not classified,Country/Territory
1,AFE,Aggregates,NaN,Aggregates,Aggregates,Aggregate
2,AFG,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,IDA,Country/Territory
3,AFR,Aggregates,NaN,Aggregates,Aggregates,Aggregate
4,AFW,Aggregates,NaN,Aggregates,Aggregates,Aggregate
5,AGO,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Country/Territory
6,ALB,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Country/Territory
7,AND,Europe & Central Asia,NaN,High income,Not classified,Country/Territory
8,ARB,Aggregates,NaN,Aggregates,Aggregates,Aggregate
9,ARE,"Middle East, North Africa, Afghanistan & Pakistan",NaN,High income,Not classified,Country/Territory

In [4]:
gdp_df = pd.read_csv(GDP_PATH, skiprows=4)

print("GDP shape:", gdp_df.shape)
gdp_df.head()

GDP shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [5]:
gdp_with_region = gdp_df.merge(
    wb_region_map,
    on="Country Code",
    how="left"
)

print("GDP with WB Region shape:", gdp_with_region.shape)
gdp_with_region[[
    "Country Name",
    "Country Code",
    "WB Region",
    "Admin Region",
    "Income Level",
    "Country Type"
]].head(15)

GDP with WB Region shape: (266, 75)

,Country Name,Country Code,WB Region,Admin Region,Income Level,Country Type
0,Aruba,ABW,Latin America & Caribbean,NaN,High income,Country/Territory
1,Africa Eastern and Southern,AFE,Aggregates,NaN,Aggregates,Aggregate
2,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,Country/Territory
3,Africa Western and Central,AFW,Aggregates,NaN,Aggregates,Aggregate
4,Angola,AGO,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Country/Territory
5,Albania,ALB,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
6,Andorra,AND,Europe & Central Asia,NaN,High income,Country/Territory
7,Arab World,ARB,Aggregates,NaN,Aggregates,Aggregate
8,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",NaN,High income,Country/Territory
9,Argentina,ARG,Latin America & Caribbean,Latin America & Caribbean (excluding high income),Upper middle income,Country/Territory
10,Armenia,ARM,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
11,American Samoa,ASM,East Asia & Pacific,NaN,High income,Country/Territory
12,Antigua and Barbuda,ATG,Latin America & Caribbean,NaN,High income,Country/Territory
13,Australia,AUS,East Asia & Pacific,NaN,High income,Country/Territory
14,Austria,AUT,Europe & Central Asia,NaN,High income,Country/Territory

In [6]:
gdp_unmapped = gdp_with_region[gdp_with_region["WB Region"].isna()][[
    "Country Name",
    "Country Code"
]]

print("Number of unmapped rows in GDP:", gdp_unmapped.shape[0])
gdp_unmapped.drop_duplicates().head(20)

Number of unmapped rows in GDP: 0

Empty DataFrame
Columns: [Country Name, Country Code]
Index: []

In [7]:

life_df = pd.read_csv(LIFE_PATH, skiprows=4)

print("Life Expectancy shape:", life_df.shape)
life_df.head()

Life Expectancy shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.049000,64.215000,64.602000,64.944000,65.303000,65.615000,...,75.540000,75.620000,75.880000,76.019000,75.406000,73.655000,76.226000,76.353000,NaN,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.169658,44.468838,44.877890,45.160583,45.535695,45.770723,...,62.167981,62.591275,63.330691,63.857261,63.766484,62.979999,64.487020,65.146154,NaN,NaN
2,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.799000,33.291000,33.757000,34.201000,34.673000,35.124000,...,62.646000,62.406000,62.443000,62.941000,61.454000,60.417000,65.617000,66.035000,NaN,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.779636,38.058956,38.681792,38.936918,39.194580,39.479784,...,56.392452,56.626439,57.036976,57.149847,57.364425,57.362572,57.987813,58.855722,NaN,NaN
4,Angola,AGO,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.933000,36.902000,37.168000,37.419000,37.704000,37.968000,...,61.619000,62.122000,62.622000,63.051000,63.116000,62.958000,64.246000,64.617000,NaN,NaN

In [8]:
life_with_region = life_df.merge(
    wb_region_map,
    on="Country Code",
    how="left"
)

print("Life Expectancy with WB Region shape:", life_with_region.shape)
life_with_region[[
    "Country Name",
    "Country Code",
    "WB Region",
    "Admin Region",
    "Income Level",
    "Country Type"
]].head(15)

Life Expectancy with WB Region shape: (266, 75)

,Country Name,Country Code,WB Region,Admin Region,Income Level,Country Type
0,Aruba,ABW,Latin America & Caribbean,NaN,High income,Country/Territory
1,Africa Eastern and Southern,AFE,Aggregates,NaN,Aggregates,Aggregate
2,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,Country/Territory
3,Africa Western and Central,AFW,Aggregates,NaN,Aggregates,Aggregate
4,Angola,AGO,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Country/Territory
5,Albania,ALB,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
6,Andorra,AND,Europe & Central Asia,NaN,High income,Country/Territory
7,Arab World,ARB,Aggregates,NaN,Aggregates,Aggregate
8,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",NaN,High income,Country/Territory
9,Argentina,ARG,Latin America & Caribbean,Latin America & Caribbean (excluding high income),Upper middle income,Country/Territory
10,Armenia,ARM,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
11,American Samoa,ASM,East Asia & Pacific,NaN,High income,Country/Territory
12,Antigua and Barbuda,ATG,Latin America & Caribbean,NaN,High income,Country/Territory
13,Australia,AUS,East Asia & Pacific,NaN,High income,Country/Territory
14,Austria,AUT,Europe & Central Asia,NaN,High income,Country/Territory

In [9]:
life_unmapped = life_with_region[life_with_region["WB Region"].isna()][[
    "Country Name",
    "Country Code"
]]

print("Number of unmapped rows in Life Expectancy:", life_unmapped.shape[0])
life_unmapped.drop_duplicates().head(20)

Number of unmapped rows in Life Expectancy: 0

Empty DataFrame
Columns: [Country Name, Country Code]
Index: []

In [10]:
pop_df = pd.read_csv(POP_PATH, skiprows=4)

print("Population shape:", pop_df.shape)
pop_df.head()

Population shape: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

In [11]:
pop_with_region = pop_df.merge(
    wb_region_map,
    on="Country Code",
    how="left"
)

print("Population with WB Region shape:", pop_with_region.shape)
pop_with_region[[
    "Country Name",
    "Country Code",
    "WB Region",
    "Admin Region",
    "Income Level",
    "Country Type"
]].head(15)

Population with WB Region shape: (266, 75)

,Country Name,Country Code,WB Region,Admin Region,Income Level,Country Type
0,Aruba,ABW,Latin America & Caribbean,NaN,High income,Country/Territory
1,Africa Eastern and Southern,AFE,Aggregates,NaN,Aggregates,Aggregate
2,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,Country/Territory
3,Africa Western and Central,AFW,Aggregates,NaN,Aggregates,Aggregate
4,Angola,AGO,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Country/Territory
5,Albania,ALB,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
6,Andorra,AND,Europe & Central Asia,NaN,High income,Country/Territory
7,Arab World,ARB,Aggregates,NaN,Aggregates,Aggregate
8,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",NaN,High income,Country/Territory
9,Argentina,ARG,Latin America & Caribbean,Latin America & Caribbean (excluding high income),Upper middle income,Country/Territory
10,Armenia,ARM,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,Country/Territory
11,American Samoa,ASM,East Asia & Pacific,NaN,High income,Country/Territory
12,Antigua and Barbuda,ATG,Latin America & Caribbean,NaN,High income,Country/Territory
13,Australia,AUS,East Asia & Pacific,NaN,High income,Country/Territory
14,Austria,AUT,Europe & Central Asia,NaN,High income,Country/Territory

In [12]:
pop_unmapped = pop_with_region[pop_with_region["WB Region"].isna()][[
    "Country Name",
    "Country Code"
]]

print("Number of unmapped rows in Population:", pop_unmapped.shape[0])
pop_unmapped.drop_duplicates().head(20)

Number of unmapped rows in Population: 0

Empty DataFrame
Columns: [Country Name, Country Code]
Index: []

In [13]:
print("GDP - WB Region distribution")
display(gdp_with_region["WB Region"].value_counts(dropna=False).to_frame("count"))

print("Life Expectancy - WB Region distribution")
display(life_with_region["WB Region"].value_counts(dropna=False).to_frame("count"))

print("Population - WB Region distribution")
display(pop_with_region["WB Region"].value_counts(dropna=False).to_frame("count"))

GDP - WB Region distribution

                                                   count
WB Region
Europe & Central Asia                                 58
Aggregates                                            49
Sub-Saharan Africa                                    48
Latin America & Caribbean                             42
East Asia & Pacific                                   37
Middle East, North Africa, Afghanistan & Pakistan     23
South Asia                                             6
North America                                          3

Life Expectancy - WB Region distribution

                                                   count
WB Region
Europe & Central Asia                                 58
Aggregates                                            49
Sub-Saharan Africa                                    48
Latin America & Caribbean                             42
East Asia & Pacific                                   37
Middle East, North Africa, Afghanistan & Pakistan     23
South Asia                                             6
North America                                          3

Population - WB Region distribution

                                                   count
WB Region
Europe & Central Asia                                 58
Aggregates                                            49
Sub-Saharan Africa                                    48
Latin America & Caribbean                             42
East Asia & Pacific                                   37
Middle East, North Africa, Afghanistan & Pakistan     23
South Asia                                             6
North America                                          3

In [14]:
gdp_country_only = gdp_with_region[gdp_with_region["Country Type"] == "Country/Territory"].copy()
life_country_only = life_with_region[life_with_region["Country Type"] == "Country/Territory"].copy()
pop_country_only = pop_with_region[pop_with_region["Country Type"] == "Country/Territory"].copy()

print("GDP country-only shape:", gdp_country_only.shape)
print("Life country-only shape:", life_country_only.shape)
print("Population country-only shape:", pop_country_only.shape)

GDP country-only shape: (217, 75)
Life country-only shape: (217, 75)
Population country-only shape: (217, 75)

In [15]:
gdp_with_region.to_csv("/Users/tonytony/Final Project/Data/Raw/gdp_with_wb_region.csv", index=False)
life_with_region.to_csv("/Users/tonytony/Final Project/Data/Raw/life_with_wb_region.csv", index=False)
pop_with_region.to_csv("/Users/tonytony/Final Project/Data/Raw/pop_with_wb_region.csv", index=False)

print("Saved:")
print("gdp_with_wb_region.csv")
print("life_with_wb_region.csv")
print("pop_with_wb_region.csv")

Saved:
gdp_with_wb_region.csv
life_with_wb_region.csv
pop_with_wb_region.csv